### ISSUE TITLE
How can I run the interactive notebook

### ISSUE THREAD

**Issue by FantasyVR** [SciML/DiffEqTutorials.jl#157]
I've install Julia and jupyter notebook. After that what should I do? 
 I don't understand
> install the package and open the tutorials like:

Is it a pakcage manager or something else?  How can I install that package?
Where should I type in the command
```
using Pkg
pkg"add https://github.com/JuliaDiffEq/DiffEqTutorials.jl"
using DiffEqTutorials
DiffEqTutorials.open_notebooks()
```

**Comment by KZiemian** [comment]
Contact me at kziemianfvt@gmail.com and I will help you as much as I can. There is no reason to talking about this in GitHub issue, here we should discusse on other topics.

**Comment by SebastianM-C** [comment]
> Where should I type in the command

In the julia REPL.
