### ISSUE TITLE
Have a script to automatically detect changes to a tutorial and weave those tutorials

### ISSUE THREAD

**Issue by Vaibhavdixit02** [SciML/DiffEqTutorials.jl#161]
I found the https://github.com/TuringLang/TuringTutorials/blob/master/render-example.bash a neat idea, would definitely make it much easier to work on the tutorials.

**Comment by ChrisRackauckas** [comment]
We're working on it. Buying new hardware this week actually.

**Comment by ChrisRackauckas** [comment]
!rebuild introduction/01-ode_introduction.jmd

**Comment by christopher-dG** [comment]
This was triggered correctly, but the mirroring hasn't updated so there's no `.gitlab-ci.yml` on master. Wait like 30 minutes and it should be good to go. https://github.com/SciML/DiffEqTutorials.jl/runs/773374645?check_suite_focus=true

In the meantime, I'll add a reply or reaction to confirm that your comment was detected.

**Comment by christopher-dG** [comment]
!rebuild introduction/01-ode_introduction.jmd

this should work now

**Comment by christopher-dG** [comment]
success

https://github.com/SciML/DiffEqTutorials.jl/runs/773573902?check_suite_focus=true
https://gitlab.com/JuliaGPU/DiffEqTutorials.jl/-/pipelines/156447496

**Comment by christopher-dG** [comment]
!rebuild introduction/01-ode_introduction.jmd

crossing my fingers this time...
