### ISSUE TITLE
Bug in 08 Kolmogorov.jl

### ISSUE THREAD

**Issue by finmod** [SciML/DiffEqTutorials.jl#168]
In m = fmap(cpu , m)      "cu" should be "cpu"

**Comment by finmod** [comment]
And another one further down: 

prob = SDEProblem(f_val,g_val,u₀,tspan) instead of prob = SDEProblem(f,g,u₀,tspan)

For: @time sol = solve(prob, NeuralNetDiffEq.NNKolmogorov(m, opt, sdealg, ensemblealg), verbose = true, dt = dt,
            dx = dx , trajectories = trajectories , abstol=1e-6, maxiters = 3000)

takes:
Current loss is: 288.77471066944065
Current loss is: 288.7747063768811
15327.516623 seconds (174.48 G allocations: 9.600 TiB, 11.89% gc time)
([105.83 108.06 … 105.32 107.2], Float32[11.2977295 10.500775 … 11.479994 10.80812])

4 hours and 15 minutes!!!

**Comment by ChrisRackauckas** [comment]
I haven't built it yet to see. @ashutosh-b-b that looks incorrect though if the loss doesn't change?

**Comment by finmod** [comment]
Also add 'using Distributions' to calculate mean(phi)

**Comment by ChrisRackauckas** [comment]
`using Statistics` I think

**Comment by ChrisRackauckas** [comment]
@ashutosh-b-b it's worth a few fixes here. Notice I refactored a bit in https://github.com/SciML/DiffEqTutorials.jl/pull/169

**Comment by ChrisRackauckas** [comment]
rebuild! advanced/03-kolmogorov_equations

**Comment by ChrisRackauckas** [comment]
!rebuild advanced/03-kolmogorov_equations.jmd

**Comment by ChrisRackauckas** [comment]
Fixed!

**Comment by finmod** [comment]
Great. 427 seconds by steeping back to CuArrays and CUDAnative. Hopefully, CUDA.jl on Windows will pass its tests soon.
